### ISSUE TITLE
not working in Linux Arch

### ISSUE THREAD

**Issue by zeekus** [learncodebygaming/pydirectinput#48]
This python library is not working for me in Arch Linux. What is this windll dependency ? 

source: simple.py

```
import pyautogui
import pydirectinput
pydirectinput.moveTo(100, 150) # Move the mouse to the x, y coordinates 100, 150.
```

I get this error on running it.
```
[zeekus@archlinux ~]$ python3 simple.py 
Traceback (most recent call last):
  File "/home/zeekus/simple.py", line 2, in <module>
    import pydirectinput
  File "/home/zeekus/.local/lib/python3.10/site-packages/pydirectinput/__init__.py", line 6, in <module>
    SendInput = ctypes.windll.user32.SendInput
AttributeError: module 'ctypes' has no attribute 'windll'
```

**Comment by italojohnny** [comment]
same problem here

**Comment by talha-atif** [comment]
Anyone found a solution?

**Comment by Anonymous3-a** [comment]
Because pydirectinput is for windows direct input. It's useful for, eg, scripting roblox (I write scripts to automate things for a friend). Just use pyautogui, come on.
